# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WATCH_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(121, 205, 205);\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                  stop:0 white, stop: 0.04 rgb(151, 224, 238), stop:1  rgb(165, 134, 242));\n"
"    font: 11pt \"Tw Cen MT Condensed Extra Bold\";\n"
"    \n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(175, 255, 255);\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                  stop:0 white, stop: 0.04 rgb(171, 244, 250), stop:1  rgb(185, 154, 242));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 60px;\n"
"    background-color: rgb(17, 27, 33);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(60, 230, 75, 23))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 230, 75, 23))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 230, 75, 23))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(70, 180, 311, 31))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(124, 113, 116);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    font: 18pt \"Tw Cen MT Condensed Extra Bold\";\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop: 0\n"
"rgba(174, 82, 194, 255), stop: 1 rgba(111, 109, 174, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop: 0\n"
"rgba(201, 87, 149, 255), stop: 1 rgba(179, 65, 244, 255));\n"
"}")
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly|QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly|QtCore.Qt.ImhUrlCharactersOnly)
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.Time = QtWidgets.QLineEdit(self.frame)
        self.Time.setGeometry(QtCore.QRect(62, 59, 331, 101))
        self.Time.setStyleSheet("QLineEdit{\n"
"    font: 40pt \"Tw Cen MT Condensed Extra Bold\";\n"
"    border-radius: 60px;\n"
"    background-color: rgb(17, 27, 33);\n"
"    color:  rgb(121, 205, 205);\n"
"    \n"
"}\n"
"")
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setReadOnly(True)
        self.Time.setObjectName("Time")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "СТАРТ"))
        self.pushButton_2.setText(_translate("MainWindow", "ПАУЗА"))
        self.pushButton_3.setText(_translate("MainWindow", "СБРОС"))
        self.Time.setText(_translate("MainWindow", "00 : 00 : 00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
